# Steps to run the docker file
# use sudo based on your host machine (for linux)
# docker build -t ub:latest .

FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils build-essential sudo git
